project:
  type: book
  output-dir: docs
  


book:
  title: "MOSAIC Calculus"
  author: "Daniel Kaplan"
  date: "4/28/2022"
  chapters:
    - index.qmd
    # - intro.qmd
    # - part: preliminaries-part.qmd
    #   chapters:
    #     - Preliminaries/01-modeling-change.Rmd
    #     - Preliminaries/02-notation.Rmd
    #     - Preliminaries/03-computing.Rmd
    #     - Preliminaries/04-graphs-and-graphics.Rmd
    #     - Preliminaries/05-pattern-book-functions.Rmd
    #     - Preliminaries/06-describing-functions.Rmd
    #     - Preliminaries/07-data-and-data-graphics.Rmd
    # - part: modeling-part.qmd
    #   chapters:
    #     - Modeling/01-parameters.Rmd
    #     - Modeling/02-assembling-functions.Rmd
    #     - Modeling/03-functions-with-multiple-inputs.Rmd
    #     - Modeling/04-fitting-by-eye.Rmd
    #     - Modeling/05-low-order-polynomials.Rmd
    #     - Modeling/06-operations.Rmd
    #     - Modeling/07-magnitudes.Rmd
    #     - Modeling/08-dimensions.Rmd
    #     - Modeling/09-modeling-cycle.Rmd
    - part: differentiation-part.qmd
      chapters:
         - Differentiation/16-continuous-change.Rmd
         # - Differentiation/17-rate-of-change.Rmd
         - Differentiation/18-evanescent-h.Rmd
         - Differentiation/19-computing.Rmd
    #     - Differentiation/20-concavity.Rmd
    #     - Differentiation/21-cont-and-smooth.Rmd
    #     - Differentiation/22-rules.Rmd
    #     - Differentiation/23-optim.Rmd
    #     - Differentiation/24-partial.Rmd
    #     - Differentiation/25-approximation.Rmd
    #     - Differentiation/26-taylor.Rmd
    # - part: linear-combinations-part.qmd
    #   chapters:
    #     - Linear-combinations/B5-Vectors.Rmd
    #     - Linear-combinations/B5-linear-combinations.Rmd
    #     - Linear-combinations/B5-projection.Rmd
    #     - Linear-combinations/B5-target-problem.Rmd
    #     - Linear-combinations/B5-stat-modeling.Rmd
    #     - Linear-combinations/B5-functions.Rmd
    # - part: accumulation-part.qmd
    #   chapters:
    #     - Accumulation/27-intro.Rmd
    #     - Accumulation/28-visualizing.Rmd
    #     - Accumulation/29-integration.Rmd
    #     - Accumulation/30-euler.Rmd
    #     - Accumulation/31-symbolic.Rmd
    # 
    # - part: dynamics-part.qmd
    #   chapters:
    #     - Dynamics/B6-diff-eq.Rmd
    #     - Dynamics/B6-solution.Rmd
    #     - Dynamics/B6-flow-on-line.Rmd
    #     - Dynamics/B6-flow-on-plane.Rmd
    #     - Dynamics/B6-modeling.Rmd
    #     - Dynamics/B6-equilibria.Rmd
    #     - Dynamics/B6-eigen.Rmd
    #     - Dynamics/B6-second-order.Rmd
    #     # - Dynamics/B6-forcing.Rmd
    # - part: manifestations-part.qmd
    #   chapters:
    #     - Manifestations/B4-operations.Rmd
    #     - Manifestations/B4-splines.Rmd
    #     - Manifestations/B4-optimization.Rmd
    #     - Manifestations/B4-probability.Rmd
    #     - Manifestations/B4-future-value.Rmd
    #     - Manifestations/B4-mechanics.Rmd
    #     # - Preliminaries/exercise-layout.qmd
  crossref:
    chapters: true 
  reference-location: margin
  citation-location: margin
  site-url: https://dtkaplan.github.io/MC2/
  repo-url: https://github.com/dtkaplan/MC2/
  repo-branch: main
  repo-actions: [edit]
  

comments: 
  hypothesis: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: mosaic-calc-style.css
    include-in-header: 
      - mathjax-definitions.html
  pdf:
    documentclass: scrreprt
    include-in-header: 
      - latex-definitions.tex
    always_allow_html: true
    keep-tex: true
    reference-location: margin
    citation-location: margin

