project:
  type: book
  output-dir: docs

book:
  title: "MOSAIC Calculus"
  author: "Daniel Kaplan"
  date: "4/6/2022"
  chapters:
    - index.qmd
    # - intro.qmd
    # - Preliminaries/01-modeling-change.Rmd
    # - Preliminaries/02-notation.Rmd
    # - Preliminaries/03-graphs-and-graphics.Rmd
    # - Preliminaries/04-pattern-book-functions.Rmd
    # - Preliminaries/05-describing-functions.Rmd
    # - Preliminaries/06-data-and-data-graphics.Rmd
    # - Modeling/01-parameters.Rmd
    - Modeling/02-assembling-functions.Rmd
    # - summary.qmd
    # - references.qmd
  crossref:
    chapters: true 
  reference-location: margin
  citation-location: margin
  site-url: https://dtkaplan.github.io/MC2/
  repo-url: https://github.com/dtkaplan/MC2/
  repo-branch: main
  repo-actions: [edit]

comments: 
  hypothesis: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: mosaic-calc-style.css
    include-in-header: 
      - mathjax-definitions.html
  pdf:
    documentclass: scrreprt
    include-in-header: 
      - latex-definitions.tex
    always_allow_html: true

