project:
  type: book
  output-dir: docs

book:
  title: "MOSAIC Calculus"
  author: "Daniel Kaplan"
  date: "4/6/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - Preliminaries/01-modeling-change.Rmd
    - Preliminaries/02-notation.Rmd
    - Preliminaries/03-graphs-and-graphics.Rmd
    - summary.qmd
    - references.qmd
  crossref:
    chapters: true 
  reference-location: margin
  citation-location: margin
  site-url: https://dtkaplan.github.io/MC2/
  repo-url: https://github.com/dtkaplan/MC2/
  repo-branch: master
  repo-actions: [edit]

comments: 
  hypothesis: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: mosaic-calc-style.css
  pdf:
    documentclass: scrreprt
    always_allow_html: true

